# Generated by Django 4.2 on 2023-07-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ProductCategory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Product_quantity', models.PositiveIntegerField()),
                ('Product_desc', models.TextField(default=' Product description not available')),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('Product_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product_category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=200)),
                ('Content', models.TextField(default='Content not available')),
                ('Pub_date', models.DateTimeField(auto_now_add=True)),
                ('Tags', models.ManyToManyField(to='admin_panel.blogtags')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
