# Generated by Django 4.2.3 on 2023-08-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
