# Generated by Django 4.2.3 on 2023-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topa_payment', '0005_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
